---
- hosts: apps-laz-prod
  name: application bootstrap
  become: yes
  roles:
    - role: apps
      vars:
        ecr_images: 
          - '223580977021.dkr.ecr.ap-southeast-1.amazonaws.com/lazada/host2host'