---
- hosts: sftp
  name: sftp bootstrap
  become: yes
  roles:
    - role: sftp
      vars:
        sftp:
          user:
            create_user: false
            developer: 
              password: mchNjNXG8RTDaa5
              group_of: developer_sftp
          group:
              create_group: true
              name:
                - developer_sftp