---
- name: Download the cloudflared Linux package.
  shell: wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
- name: Depackage cloudflared.
  shell: sudo dpkg -i cloudflared-linux-amd64.deb
- name: Create a cloudflared service directory.
  shell: mkdir -p /etc/cloudflared/
- name: Create the config file for cloudflared and define the ingress rules for the tunnel.
  copy:
    dest: "/etc/cloudflared/config.yml"
    content: |
      tunnel: "{{ tunnel_id }}"
      credentials-file: /etc/cloudflared/cert.json
      logfile: /var/log/cloudflared.log
      loglevel: info
      ingress:
        - hostname: "{{ ssh_service }}"
          service: ssh://localhost:22
        - hostname: "{{ app_service }}"
          service: http://localhost:8000
        - service: http_status:404

- name: Create the tunnel credentials file for cloudflared.
  copy:
    dest: "/etc/cloudflared/cert.json"
    content: |
      {
        "AccountTag"   : "{{ account_id | quote }}",
        "TunnelID"     : "{{ tunnel_id | quote }}",
        "TunnelName"   : "{{ tunnel_name | quote }}",
        "TunnelSecret" : "{{ secret | quote }}"
      }

- name: check services
  service_facts:

- name: Install the tunnel as a systemd service.
  shell: cloudflared service install
  when: "'cloudflared.service' not in ansible_facts['services']"


- name: Start the tunnel.
  systemd:
    name: cloudflared
    state: restarted
    enabled: true
    masked: no

- name: Delete the downloaded packages.
  shell: rm -f cloudflared-linux-amd64*