version: '3.9'
services:

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ~/var/lib/rabbitmq:/var/lib/rabbitmq
      - ~/var/log/rabbitmq:/var/log/rabbitmq
    ports:
      # - "5672:5672"
      - "15672:15672"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:
      test: "rabbitmq-diagnostics -q ping || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s

  backend:
    image: 252322529613.dkr.ecr.ap-southeast-1.amazonaws.com/lazada/host2host:${IMG_TAG}
    restart: always
    command: gunicorn -b 0.0.0.0 --workers 2 host2host.wsgi
    ports:
      - "8000:8000"
    env_file: .env.laz_prod
    environment:
      - DEBUG=True
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:
      test: "curl --fail http://localhost:8000/api/health-check || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s

  queue_default:
    image: 252322529613.dkr.ecr.ap-southeast-1.amazonaws.com/lazada/host2host:${IMG_TAG}
    restart: always
    command: celery -A celery_tasks worker -l info -B --autoscale=10,1 -n worker1@%h
    env_file: .env.laz_prod
    environment:
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - ~/.ssh/id_ed25519:/root/.ssh/id_key
    depends_on:
      - rabbitmq
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:
      test: "celery -A celery_tasks inspect ping || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
  
  celery_flower:
    image: 252322529613.dkr.ecr.ap-southeast-1.amazonaws.com/lazada/host2host:${IMG_TAG}
    restart: always
    command: celery -A celery_tasks flower
    env_file: .env.laz_prod
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  
  nginx_manager:
    hostname: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - ~/var/lib/nginx-proxy-manager/data:/data
      - ~/var/lib/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
